### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by yangyangnau** [zwliew/android_device_xiaomi_land#1]
I'm failed to build CM-13 with your device tree and my porting kernel.
Where are paths "vendor/cm/device/product" and "vendor/cm/device/board"?
I had checked https://github.com/CyanogenMod/android_vendor_cm.
no luck. 

PS:
You probably want to check my porting kernel for Redmi 3S.
The cameras and fingerprint don't work yet. Help is wellcome.
https://github.com/yangyangnau/andro...xiaomi_msm8937
https://github.com/yangyangnau/andro...ment-258682130
http://forum.xda-developers.com/xiao...dmi3s-t3469965
also check:
https://github.com/assusdan/android_...xiaomi_msm8937
https://github.com/supercairos/andro...xiaomi_msm8937

**Comment by zwliew** [comment]
Here they are: http://review.cyanogenmod.org/#/c/168243/

**Comment by yangyangnau** [comment]
Thanks!
After fixing zram.mk, I can build CM-13 now.
`git revert 6a41f98d1d4a3291c7037b062cb9ce7911a59909`

**Comment by yangyangnau** [comment]
I can build now with commit 8c817cc.
But the CM-13 just show the mi logo. I will check it tomorrow.

**Comment by yangyangnau** [comment]
After remove /system/vendor/lib64/libsdmextension.so, the CM-13 can boot.
The /system/lib/modules/core_ctl.ko is useless for custom kernel.

**Comment by kondors1995** [comment]
I am havving same issue how do you fixed it?
