### ISSUE TITLE
Unappropriate Path in Boardconfig.mk

### ISSUE THREAD

**Issue by flsagarjain** [zwliew/android_device_xiaomi_land#7]
Hello @zwliew 
I am currently trying to develop cm-13 for this device.
I am getting an error while brunch.
The error is due to CM_PATH := vendor/cm/config/board this path.
In my synced Cm-13 there is no such folder named as "board" in the following directory vendor/cm/config.
Please help me out with this error.
p.s: I do not have much knowledge about this and I am new at rom building.
Thanks

**Comment by zwliew** [comment]
Follow the instructions here https://github.com/zwliew/android_kernel_xiaomi_msm8937/issues/4

**Comment by flsagarjain** [comment]
I dont understand? What I have to do? I have read the complete post...but didn't get it.Do I have to edit roomservice.xml? I have already done it.The issue is with the device tree.Please Elaborate ..I am a learner.

**Comment by zwliew** [comment]
Look at my very last post. You have to cherry-pick a patch.

**Comment by flsagarjain** [comment]
Now getting this error :- 
target  C++: recovery <= bootable/recovery/asn1_decoder.cpp
../../../../../../kernel/xiaomi/msm8937/kernel/sched/core.c: In function 'sched_set_cluster_dstate':
../../../../../../kernel/xiaomi/msm8937/kernel/sched/core.c:818:38: error: 'struct rq' has no member named 'cluster'
   cpu_rq(cpumask_first(cluster_cpus))->cluster;
                                      ^
../../../../../../kernel/xiaomi/msm8937/kernel/sched/core.c:819:9: error: dereferencing pointer to incomplete type
  cluster->dstate = dstate;
         ^
../../../../../../kernel/xiaomi/msm8937/kernel/sched/core.c:820:9: error: dereferencing pointer to incomplete type
  cluster->dstate_wakeup_energy = wakeup_energy;
         ^
../../../../../../kernel/xiaomi/msm8937/kernel/sched/core.c:821:9: error: dereferencing pointer to incomplete type
  cluster->dstate_wakeup_latency = wakeup_latency;
         ^
../../../../../../kernel/xiaomi/msm8937/kernel/sched/core.c: In function 'sched_init_smp':
../../../../../../kernel/xiaomi/msm8937/kernel/sched/core.c:9853:2: error: implicit declaration of function 'update_cluster_topology' [-Werror=implicit-function-declaration]
  update_cluster_topology();
  ^
cc1: some warnings being treated as errors
/home/sagar/cm/kernel/xiaomi/msm8937/scripts/Makefile.build:257: recipe for target 'kernel/sched/core.o' failed
make[4]: *** [kernel/sched/core.o] Error 1
/home/sagar/cm/kernel/xiaomi/msm8937/scripts/Makefile.build:402: recipe for target 'kernel/sched' failed
make[3]: *** [kernel/sched] Error 2
/home/sagar/cm/kernel/xiaomi/msm8937/Makefile:948: recipe for target 'kernel' failed
make[2]: *** [kernel] Error 2
make[2]: Leaving directory '/home/sagar/cm/out/target/product/land/obj/KERNEL_OBJ'
Makefile:145: recipe for target 'sub-make' failed
make[1]: *** [sub-make] Error 2
make[1]: Leaving directory '/home/sagar/cm/kernel/xiaomi/msm8937'
build/core/tasks/kernel.mk:292: recipe for target 'TARGET_KERNEL_BINARIES' failed

**Comment by flsagarjain** [comment]
Any Help @zwliew

**Comment by flsagarjain** [comment]
Build Successful ...Thank You @zwliew
